#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]
then
    . /usr/share/debconf/confmodule
fi

db_get keystone/configure_db
if [ "$RET" = "true" ] && [ -f /etc/dbconfig-common/keystone.conf ] ; then
    if [ -f /usr/share/dbconfig-common/dpkg/postrm ]
    then
	. /usr/share/dbconfig-common/dpkg/postrm
	dbc_go keystone $@
    fi
fi

case "$1" in
    purge)
        rm -rf /var/log/keystone
	rm -rf /var/lib/keystone
	rm -rf /etc/keystone
esac

#DEBHELPER#
